const testData = [
  {
    created_at: 'Sun Jan 24 23:59:10 +0000 2021',
    id: 1353492572849791000,
    id_str: '1353492572849790977',
    full_text: '💚🍻💚 https://t.co/YhGKQEUfcL',
    truncated: false,
    display_text_range: [0, 3],
    entities: {
      hashtags: [],
      symbols: [],
      user_mentions: [],
      urls: [
        {
          url: 'https://t.co/YhGKQEUfcL',
          expanded_url: 'https://twitter.com/matts/status/1353466200689233920',
          display_url: 'twitter.com/matts/status/1…',
          indices: [4, 27],
        },
      ],
    },
    source:
      '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 16721886,
      id_str: '16721886',
      name: 'Dogfish Head Brewery',
      screen_name: 'dogfishbeer',
      location: 'Milton, DE',
      description:
        'Off-centered goodness for off-centered people. Brewery, Restaurants, Distillery & Inn! Followers must be 21+, cheers! • 6 Cannery Village, Milton, DE 19968',
      url: 'https://t.co/1gQzOP9Tuu',
      entities: {
        url: {
          urls: [
            {
              url: 'https://t.co/1gQzOP9Tuu',
              expanded_url: 'http://www.dogfish.com',
              display_url: 'dogfish.com',
              indices: [0, 23],
            },
          ],
        },
        description: {
          urls: [],
        },
      },
      protected: false,
      followers_count: 286780,
      friends_count: 2180,
      listed_count: 6808,
      created_at: 'Mon Oct 13 15:11:33 +0000 2008',
      favourites_count: 22890,
      utc_offset: null,
      time_zone: null,
      geo_enabled: true,
      verified: true,
      statuses_count: 47901,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: '130300',
      profile_background_image_url:
        'http://abs.twimg.com/images/themes/theme1/bg.png',
      profile_background_image_url_https:
        'https://abs.twimg.com/images/themes/theme1/bg.png',
      profile_background_tile: false,
      profile_image_url:
        'http://pbs.twimg.com/profile_images/618045650119335936/S0CaWOpQ_normal.jpg',
      profile_image_url_https:
        'https://pbs.twimg.com/profile_images/618045650119335936/S0CaWOpQ_normal.jpg',
      profile_banner_url:
        'https://pbs.twimg.com/profile_banners/16721886/1401887234',
      profile_link_color: '126249',
      profile_sidebar_border_color: '130300',
      profile_sidebar_fill_color: 'A27E52',
      profile_text_color: '130300',
      profile_use_background_image: true,
      has_extended_profile: true,
      default_profile: false,
      default_profile_image: false,
      following: true,
      follow_request_sent: false,
      notifications: false,
      translator_type: 'none',
    },
    geo: null,
    coordinates: null,
    place: {
      id: '004334fc1107481f',
      url: 'https://api.twitter.com/1.1/geo/id/004334fc1107481f.json',
      place_type: 'city',
      name: 'Milton',
      full_name: 'Milton, DE',
      country_code: 'US',
      country: 'United States',
      contained_within: [],
      bounding_box: {
        type: 'Polygon',
        coordinates: [
          [
            [-75.32726, 38.768874],
            [-75.30262, 38.768874],
            [-75.30262, 38.791145],
            [-75.32726, 38.791145],
          ],
        ],
      },
      attributes: {},
    },
    contributors: null,
    is_quote_status: true,
    quoted_status_id: 1353466200689234000,
    quoted_status_id_str: '1353466200689233920',
    quoted_status_permalink: {
      url: 'https://t.co/YhGKQEUfcL',
      expanded: 'https://twitter.com/matts/status/1353466200689233920',
      display: 'twitter.com/matts/status/1…',
    },
    quoted_status: {
      created_at: 'Sun Jan 24 22:14:23 +0000 2021',
      id: 1353466200689234000,
      id_str: '1353466200689233920',
      full_text: 'one of those timeless beers for me. https://t.co/q2hnSP5Mbo',
      truncated: false,
      display_text_range: [0, 35],
      entities: {
        hashtags: [],
        symbols: [],
        user_mentions: [],
        urls: [],
        media: [
          {
            id: 1353466194611875800,
            id_str: '1353466194611875840',
            indices: [36, 59],
            media_url: 'http://pbs.twimg.com/media/Esh6VUFXMAAYfzk.jpg',
            media_url_https: 'https://pbs.twimg.com/media/Esh6VUFXMAAYfzk.jpg',
            url: 'https://t.co/q2hnSP5Mbo',
            display_url: 'pic.twitter.com/q2hnSP5Mbo',
            expanded_url:
              'https://twitter.com/matts/status/1353466200689233920/photo/1',
            type: 'photo',
            sizes: {
              thumb: {
                w: 150,
                h: 150,
                resize: 'crop',
              },
              medium: {
                w: 675,
                h: 1200,
                resize: 'fit',
              },
              small: {
                w: 383,
                h: 680,
                resize: 'fit',
              },
              large: {
                w: 1152,
                h: 2048,
                resize: 'fit',
              },
            },
          },
        ],
      },
      extended_entities: {
        media: [
          {
            id: 1353466194611875800,
            id_str: '1353466194611875840',
            indices: [36, 59],
            media_url: 'http://pbs.twimg.com/media/Esh6VUFXMAAYfzk.jpg',
            media_url_https: 'https://pbs.twimg.com/media/Esh6VUFXMAAYfzk.jpg',
            url: 'https://t.co/q2hnSP5Mbo',
            display_url: 'pic.twitter.com/q2hnSP5Mbo',
            expanded_url:
              'https://twitter.com/matts/status/1353466200689233920/photo/1',
            type: 'photo',
            sizes: {
              thumb: {
                w: 150,
                h: 150,
                resize: 'crop',
              },
              medium: {
                w: 675,
                h: 1200,
                resize: 'fit',
              },
              small: {
                w: 383,
                h: 680,
                resize: 'fit',
              },
              large: {
                w: 1152,
                h: 2048,
                resize: 'fit',
              },
            },
          },
        ],
      },
      source:
        '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
      in_reply_to_status_id: null,
      in_reply_to_status_id_str: null,
      in_reply_to_user_id: null,
      in_reply_to_user_id_str: null,
      in_reply_to_screen_name: null,
      user: {
        id: 19770347,
        id_str: '19770347',
        name: 'Matt Sellers',
        screen_name: 'matts',
        location: 'OTP',
        description: 'mostly dad tweets. customer success @on24.',
        url: null,
        entities: {
          description: {
            urls: [],
          },
        },
        protected: false,
        followers_count: 796,
        friends_count: 1458,
        listed_count: 38,
        created_at: 'Fri Jan 30 14:57:01 +0000 2009',
        favourites_count: 2125,
        utc_offset: null,
        time_zone: null,
        geo_enabled: true,
        verified: false,
        statuses_count: 11502,
        lang: null,
        contributors_enabled: false,
        is_translator: false,
        is_translation_enabled: false,
        profile_background_color: '325667',
        profile_background_image_url:
          'http://abs.twimg.com/images/themes/theme14/bg.gif',
        profile_background_image_url_https:
          'https://abs.twimg.com/images/themes/theme14/bg.gif',
        profile_background_tile: false,
        profile_image_url:
          'http://pbs.twimg.com/profile_images/815361995025350656/CM1VSIAS_normal.jpg',
        profile_image_url_https:
          'https://pbs.twimg.com/profile_images/815361995025350656/CM1VSIAS_normal.jpg',
        profile_banner_url:
          'https://pbs.twimg.com/profile_banners/19770347/1479331872',
        profile_link_color: 'F16C00',
        profile_sidebar_border_color: 'FFFFFF',
        profile_sidebar_fill_color: 'CF2C14',
        profile_text_color: 'F5AF5A',
        profile_use_background_image: false,
        has_extended_profile: true,
        default_profile: false,
        default_profile_image: false,
        following: false,
        follow_request_sent: false,
        notifications: false,
        translator_type: 'none',
      },
      geo: null,
      coordinates: null,
      place: null,
      contributors: null,
      is_quote_status: false,
      retweet_count: 0,
      favorite_count: 27,
      favorited: false,
      retweeted: false,
      possibly_sensitive: false,
      lang: 'en',
    },
    retweet_count: 3,
    favorite_count: 41,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    lang: 'und',
  },
  {
    created_at: 'Sun Jan 24 20:35:37 +0000 2021',
    id: 1353441346347036700,
    id_str: '1353441346347036673',
    full_text: '@n_mallard We totally planned that! 😉 🍻',
    truncated: false,
    display_text_range: [11, 39],
    entities: {
      hashtags: [],
      symbols: [],
      user_mentions: [
        {
          screen_name: 'n_mallard',
          name: 'Nick Mallard',
          id: 47435033,
          id_str: '47435033',
          indices: [0, 10],
        },
      ],
      urls: [],
    },
    source:
      '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
    in_reply_to_status_id: 1353440397318623200,
    in_reply_to_status_id_str: '1353440397318623234',
    in_reply_to_user_id: 47435033,
    in_reply_to_user_id_str: '47435033',
    in_reply_to_screen_name: 'n_mallard',
    user: {
      id: 16721886,
      id_str: '16721886',
      name: 'Dogfish Head Brewery',
      screen_name: 'dogfishbeer',
      location: 'Milton, DE',
      description:
        'Off-centered goodness for off-centered people. Brewery, Restaurants, Distillery & Inn! Followers must be 21+, cheers! • 6 Cannery Village, Milton, DE 19968',
      url: 'https://t.co/1gQzOP9Tuu',
      entities: {
        url: {
          urls: [
            {
              url: 'https://t.co/1gQzOP9Tuu',
              expanded_url: 'http://www.dogfish.com',
              display_url: 'dogfish.com',
              indices: [0, 23],
            },
          ],
        },
        description: {
          urls: [],
        },
      },
      protected: false,
      followers_count: 286780,
      friends_count: 2180,
      listed_count: 6808,
      created_at: 'Mon Oct 13 15:11:33 +0000 2008',
      favourites_count: 22890,
      utc_offset: null,
      time_zone: null,
      geo_enabled: true,
      verified: true,
      statuses_count: 47901,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: '130300',
      profile_background_image_url:
        'http://abs.twimg.com/images/themes/theme1/bg.png',
      profile_background_image_url_https:
        'https://abs.twimg.com/images/themes/theme1/bg.png',
      profile_background_tile: false,
      profile_image_url:
        'http://pbs.twimg.com/profile_images/618045650119335936/S0CaWOpQ_normal.jpg',
      profile_image_url_https:
        'https://pbs.twimg.com/profile_images/618045650119335936/S0CaWOpQ_normal.jpg',
      profile_banner_url:
        'https://pbs.twimg.com/profile_banners/16721886/1401887234',
      profile_link_color: '126249',
      profile_sidebar_border_color: '130300',
      profile_sidebar_fill_color: 'A27E52',
      profile_text_color: '130300',
      profile_use_background_image: true,
      has_extended_profile: true,
      default_profile: false,
      default_profile_image: false,
      following: true,
      follow_request_sent: false,
      notifications: false,
      translator_type: 'none',
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 1,
    favorited: false,
    retweeted: false,
    lang: 'en',
  },
  {
    created_at: 'Sun Jan 24 20:28:06 +0000 2021',
    id: 1353439453449244700,
    id_str: '1353439453449244673',
    full_text: '@Donnalee711 @SerahBAuthor 🍻🍻🍻',
    truncated: false,
    display_text_range: [27, 30],
    entities: {
      hashtags: [],
      symbols: [],
      user_mentions: [
        {
          screen_name: 'Donnalee711',
          name: 'Donna Pawlowski',
          id: 262420136,
          id_str: '262420136',
          indices: [0, 12],
        },
        {
          screen_name: 'SerahBAuthor',
          name: 'Serah Johnson 🌟💙',
          id: 1010959189831807000,
          id_str: '1010959189831806978',
          indices: [13, 26],
        },
      ],
      urls: [],
    },
    source:
      '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
    in_reply_to_status_id: 1352853724121735200,
    in_reply_to_status_id_str: '1352853724121735168',
    in_reply_to_user_id: 262420136,
    in_reply_to_user_id_str: '262420136',
    in_reply_to_screen_name: 'Donnalee711',
    user: {
      id: 16721886,
      id_str: '16721886',
      name: 'Dogfish Head Brewery',
      screen_name: 'dogfishbeer',
      location: 'Milton, DE',
      description:
        'Off-centered goodness for off-centered people. Brewery, Restaurants, Distillery & Inn! Followers must be 21+, cheers! • 6 Cannery Village, Milton, DE 19968',
      url: 'https://t.co/1gQzOP9Tuu',
      entities: {
        url: {
          urls: [
            {
              url: 'https://t.co/1gQzOP9Tuu',
              expanded_url: 'http://www.dogfish.com',
              display_url: 'dogfish.com',
              indices: [0, 23],
            },
          ],
        },
        description: {
          urls: [],
        },
      },
      protected: false,
      followers_count: 286780,
      friends_count: 2180,
      listed_count: 6808,
      created_at: 'Mon Oct 13 15:11:33 +0000 2008',
      favourites_count: 22890,
      utc_offset: null,
      time_zone: null,
      geo_enabled: true,
      verified: true,
      statuses_count: 47901,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: '130300',
      profile_background_image_url:
        'http://abs.twimg.com/images/themes/theme1/bg.png',
      profile_background_image_url_https:
        'https://abs.twimg.com/images/themes/theme1/bg.png',
      profile_background_tile: false,
      profile_image_url:
        'http://pbs.twimg.com/profile_images/618045650119335936/S0CaWOpQ_normal.jpg',
      profile_image_url_https:
        'https://pbs.twimg.com/profile_images/618045650119335936/S0CaWOpQ_normal.jpg',
      profile_banner_url:
        'https://pbs.twimg.com/profile_banners/16721886/1401887234',
      profile_link_color: '126249',
      profile_sidebar_border_color: '130300',
      profile_sidebar_fill_color: 'A27E52',
      profile_text_color: '130300',
      profile_use_background_image: true,
      has_extended_profile: true,
      default_profile: false,
      default_profile_image: false,
      following: true,
      follow_request_sent: false,
      notifications: false,
      translator_type: 'none',
    },
    geo: null,
    coordinates: null,
    place: {
      id: '004334fc1107481f',
      url: 'https://api.twitter.com/1.1/geo/id/004334fc1107481f.json',
      place_type: 'city',
      name: 'Milton',
      full_name: 'Milton, DE',
      country_code: 'US',
      country: 'United States',
      contained_within: [],
      bounding_box: {
        type: 'Polygon',
        coordinates: [
          [
            [-75.32726, 38.768874],
            [-75.30262, 38.768874],
            [-75.30262, 38.791145],
            [-75.32726, 38.791145],
          ],
        ],
      },
      attributes: {},
    },
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 1,
    favorited: false,
    retweeted: false,
    lang: 'und',
  },
]

export default testData
